
trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: ubuntu-latest
#     mac:
#       operatingSystem: macos-latest
pool:
  vmImage: $(operatingSystem)

stages:
- stage: Build
    jobs:
    - job: BuildJob
      steps:
      - bash: echo " build job"
- stage: DevDeploy
    jobs:
    - job: startDevDeploy
      steps:
      - bash: echo " dev deploy  job"
    - deployment: DevDeployJob
      strategy: 
        runOnce:
          deploy:
            steps:
            - script: echo "deploy to dev"

- stage: QADeploy
    jobs:
    - job: startQADeploy
      steps:
      - bash: echo " QA deploy  job"
    - deployment: QADeployJob
      strategy: 
        runOnce:
          deploy:
            steps:
            - script: echo "deploy to QA"



